# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login.proto
# Protobuf Python Version: 6.32.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '-rc1',
    'login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\"p\n\nLogin_Data\x12\x0f\n\x07open_ID\x18\x16 \x01(\t\x12\x14\n\x0c\x41\x63\x63\x65ss_token\x18\x1d \x01(\t\x12\x12\n\nplatForm23\x18\x17 \x01(\t\x12\x12\n\nplatForm99\x18\x63 \x01(\t\x12\x13\n\x0bplatForm100\x18\x64 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGIN_DATA']._serialized_start=15
  _globals['_LOGIN_DATA']._serialized_end=127
# @@protoc_insertion_point(module_scope)
